server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:9092
#    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092} # docker compose 실행용
    consumer:
      group-id: stock-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"